# Generated by Django 5.2.6 on 2025-09-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
